syntax = "proto3";
package vaccine;

service VaccineService {
  rpc RegisterVaccine(RegisterRequest) returns (RegisterReply);
  rpc ListVaccines(Empty) returns (VaccineListReply);
}

message RegisterRequest {
  string name = 1;
  string cpf  = 2;
  string vType = 3;
  string date = 4;  // ISO8601
}

message RegisterReply {
  bool success = 1;
  string txHash = 2;
}

// Mensagens para listagem
message Empty {}

message Vaccine {
  string name = 1;
  string cpf = 2;
  string vType = 3;
  string date = 4;
  string txHash = 5;
}

message VaccineListReply {
  repeated Vaccine vaccines = 1;
}
