version: "3.8"

services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo1:/data/db
    networks:
      - mongo-cluster
    command: ["--replSet", "rs0"]

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    ports:
      - 27018:27017
    volumes:
      - ./data/mongo2:/data/db
    networks:
      - mongo-cluster
    command: ["--replSet", "rs0"]

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    ports:
      - 27019:27017
    volumes:
      - ./data/mongo3:/data/db
    networks:
      - mongo-cluster
    command: ["--replSet", "rs0"]

  app-backend:
    build: ./app
    container_name: app-backend
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-cluster
    ports:
      - 50051:50051 # Porta gRPC

  hardhat:
    image: node:20
    container_name: hardhat
    working_dir: /app
    volumes:
      - ./blockchain:/app
    command: npx hardhat node
    ports:
      - 8545:8545
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
